auctions/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'auctions'
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path('add/<int:auction_id>', views.add_to_wishlist, name='add_to_wishlist'),
    path('watchlist', views.watchlist, name='watchlist'),
    path('categories', views.categories, name='categories'),
    path('categorized/<int:category_id>', views.categorized, name='categorized'),
    path('listing/<int:auction_id>', views.listing, name='listing'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import pathlib
import uuid
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone


class User(AbstractUser):
    phonenum = PhoneNumberField(default="+", null=True, blank=True)
    birthday = models.DateTimeField(default=None, null=True, blank=True)

class Category(models.Model):
    name = models.CharField(max_length=50)
    category_image = models.ImageField(upload_to="categories_image/")

def auction_image_handler(instance, filename):
    fpath = pathlib.Path(filename)
    new_fname = str(uuid.uuid1())
    return f"auction_images/{new_fname}{fpath.suffix}"

class Auction_image(models.Model):
    image = models.ImageField(upload_to=auction_image_handler)


class Auction_listing(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='creator')
    title = models.CharField(max_length=150)
    description = models.TextField()
    start_bid = models.FloatField()
    current_bid = models.FloatField()
    active = models.BooleanField(default=True)
    category = models.ManyToManyField(Category)
    date_created = models.DateTimeField(default=timezone.now)
    image_obj = models.OneToOneField(Auction_image, on_delete=models.CASCADE, null=True, blank=True)
    winner = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name='winner', null=True, blank=True)
    amount_of_bids = models.IntegerField(default=0)
    def get_image(self):
        return self.image_obj.image

class Bid(models.Model):
    auction = models.ForeignKey(Auction_listing, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bid = models.FloatField()
    date_created = models.DateTimeField(default=timezone.now)

class Comment(models.Model):
    auction = models.ForeignKey(Auction_listing, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField()
    date_created = models.DateTimeField(default=timezone.now)

class Watchlist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    auctions = models.ManyToManyField(Auction_listing, null=True, blank=True)
    in_watchlist = models.IntegerField(default=0)

auctions/forms.py
from django.db import models  
from django.forms import fields  
from .models import Auction_image  
from django import forms  
  
  
class UserImage(forms.ModelForm):  
    class Meta:  
        # To specify the model to be used to create form  
        model = Auction_image  
        # It includes all the fields of model  
        fields = ['image']

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from datetime import datetime
from auctions.forms import UserImage
from django.conf import settings

from .models import User, Auction_listing, Category, Auction_image, Watchlist, Bid, Comment


def index(request):
    if request.user.is_authenticated:
        context = {"listings": Auction_listing.objects.filter(active=True), "watchlist": Watchlist.objects.get(user=request.user)}
        return render(request, "auctions/index.html", context)
    else:
        context = {"listings": Auction_listing.objects.filter(active=True)}
        return render(request, "auctions/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return redirect("auctions:index")
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")

@login_required(login_url="auctions:login")
def logout_view(request):
    logout(request)
    return redirect("auctions:index")


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        birthday = request.POST["birthday"]
        phonenum = request.POST["telNo"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password, phonenum=phonenum, birthday=birthday)
            user.save()
            Watchlist.objects.create(user=user)
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return redirect("auctions:index")
    else:
        return render(request, "auctions/register.html")

@login_required(login_url="auctions:login")
def create(request):
    context = {"categories": Category.objects.all(), 'form': UserImage()}
    if request.method == "POST":
        title = request.POST["title"]
        description = request.POST["description"]
        st_bid = request.POST["bid"]
        creator = request.user
        category = [Category.objects.get(name=request.POST["category"])]
        form = UserImage(request.POST, request.FILES)
        if form.is_valid():
            image = form.cleaned_data.get("image")
        try:
            auction_image = Auction_image(image=image)
            auction_image.save()
            print("______________________________")
            auction = Auction_listing.objects.create(creator=creator, title=title, description=description, start_bid=st_bid, current_bid=st_bid, image_obj=auction_image)
            print("______________________________")
            auction.category.set(category)
            print("______________________________")
            auction.save()
        except IntegrityError:
            context["message"] = "Auction already taken"
            return render(request, "auctions/create.html", context)
        return redirect("auctions:index")
    else:
        return render(request, "auctions/create.html", context)

@login_required(login_url="auctions:login")
def add_to_wishlist(request, auction_id):
    wishlist = Watchlist.objects.get(user=request.user)
    auction = get_object_or_404(Auction_listing, id=auction_id)
    print(auction)
    wishlist.auctions.add(auction)
    wishlist.in_watchlist += 1
    wishlist.save()
    return redirect("auctions:index")

@login_required(login_url="auctions:login")
def watchlist(request):
    watchlist = Watchlist.objects.get(user=request.user)
    for auction in watchlist.auctions.all():
        print(auction)
    return render(request, "auctions/wishlist.html", {"watchlist": Watchlist.objects.get(user=request.user)})

@login_required(login_url="auctions:login")
def categories(request):
    return render(request, "auctions/categories.html", {"categories": Category.objects.all()})

@login_required(login_url="auctions:login")
def categorized(request, category_id):
    if request.user.is_authenticated:
        listing = set()
        for auction in Auction_listing.objects.filter(active=True):
            for category in auction.category.all():
                if category.id == category_id:
                    listing.add(auction)
        context = {"listings": listing, "watchlist": Watchlist.objects.get(user=request.user), "category_id": category_id}
        return render(request, "auctions/categorized.html", context)
    else:
        return render(request, "auctions/categorized.html")

@login_required(login_url="auctions:login")
def listing(request, auction_id):
    auction = Auction_listing.objects.get(id=auction_id)
    return render(request, "auctions/listing.html", {"auction": auction, "bids": Bid.objects.filter(auction=auction), "comments": Comment.objects.filter(auction=auction)})

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    {% if user.is_authenticated %}
    <h2 style="text-align: center;">Categories</h2>
    <section class="categories-grid">
        {% for category in categories %}
        <a href="{% url 'auctions:categorized' category_id=category.id %}">
            <div class="card bg-dark text-white">
                <img src="{{ category.category_image.url }}" class="card-img">
                <div class="card-img-overlay">
                    <h3 class="card-title">{{category.name}}</h3>
                </div>
            </div>
        </a>
        {% endfor%}
    </section>
    {% endif %}

{% endblock %}

auctions/templates/auctions/categorized.html
{% extends "auctions/layout.html" %}

{% block body %}
    {% if user.is_authenticated %}
    <h2>Active Listings</h2>
    {% for auction in listings %}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ auction.image_obj.image.url }}" class="img-fluid rounded-start" style="max-height: 300px;border-radius: 5px;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <div class="wishlist">
                        {% if auction not in watchlist.auctions.all %}
                        <a href="{% url 'auctions:add_to_wishlist' auction_id=auction.id %}" name='mybtn2' class="btn">Add to watchlist <i class="fa fa-heart"></i></a>
                        {% else %}
                        <a name='mybtn3' class="btn btn-disable" disabled>In watchlist <i class="fa fa-check"></i></a>
                        {% endif %}
                        </div>
                    <h5 class="card-title">{{auction.title}}</h5>
                    {% if auction.amount_of_bids == 0 %}
                    <h6 class="card-text" style="font-weight: bold;">Price: {{auction.current_bid}} &#128176;</h6>
                    {% else %}
                    <h6 class="card-text" style="font-weight: bold;">Price: {{auction.current_bid}} &#128176; <span>(bids {{auction.amount_of_bids}})</span></h6>
                    {% endif %}
                    <p class="card-text">{{auction.description}}</p>
                    <a href="{% url 'auctions:listing' auction_id=auction.id %}" name='mybtn2' class="btn-bid">Make a bid <i class="fa fa-gavel"></i></a>
                    <p class="card-text"><small class="text-muted">Created on: {{auction.date_created}}</small></p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Create new Listings</h2>
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <form action="{% url 'auctions:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" name="title" placeholder="Title">
        </div>
        <div class="form-group">
            <textarea id="description" name="description" rows="4" cols="50"></textarea>
        </div>
        <div class="form-group">
            <h4><label for="image">Upload image:</label></h4>
            {{ form.as_p}}
        </div>
        <div class="form-group">
            <input class="form-control" type="numeric" name="bid" step=0.01 placeholder="Starting bid">
        </div>
        <div class="form-group">
            <label>Category:</label>
            <select class="form-select" name="category">
                <option style="display:none"></option>
                {% for category in categories %}
                <option value="{{category.name}}"">{{category.name}}</option>
                {% endfor %}
            </select>
        </div>
        <input class="btn btn-primary" type="submit" value="Create">
    </form>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    {% if user.is_authenticated %}
    <h2>Active Listings</h2>
    {% for auction in listings %}
      <div class="card mb-3">
          <div class="row g-0">
              <div class="col-md-4">
                <img src="{{ auction.image_obj.image.url }}" class="img-fluid rounded-start" style="max-height: 300px;border-radius: 5px;">
              </div>
            <div class="col-md-8">
              <div class="card-body">
                  <div class="wishlist">
                    {% if auction not in watchlist.auctions.all %}
                    <a href="{% url 'auctions:add_to_wishlist' auction_id=auction.id %}" name='mybtn2' class="btn">Add to watchlist <i class="fa fa-heart"></i></a>
                    {% else %}
                    <a name='mybtn3' class="btn btn-disable" disabled>In watchlist <i class="fa fa-check"></i></a>
                    {% endif %}
                  </div>
                <h5 class="card-title">{{auction.title}}</h5>
                {% if auction.amount_of_bids == 0 %}
                <h6 class="card-text" style="font-weight: bold;">Price: {{auction.current_bid}} &#128176;</h6>
                {% else %}
                <h6 class="card-text" style="font-weight: bold;">Price: {{auction.current_bid}} &#128176; <span>(bids {{auction.amount_of_bids}})</span></h6>
                {% endif %}
                <p class="card-text">{{auction.description}}</p>
                <a href="{% url 'auctions:listing' auction_id=auction.id %}" name='mybtn2' class="btn-bid">Make a bid <i class="fa fa-gavel"></i></a>
                <br>
                <br>
                <p class="card-text"><small class="text-muted">Created on: {{auction.date_created}}</small></p>
              </div>
            </div>
          </div>
      </div>
    {% endfor %}
    {% endif %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create' %}">Create Your Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    {% if user.is_authenticated %}
    <h2 style="text-align: center;">Categories</h2>
    <section class="listing-grid">
        <div class="container">
            <img src="{{ auction.image_obj.image.url }}" class="img-fluid rounded-start" style="border-radius: 5px;">
        </div>
        <div class="container">
            <h2>{{auction.title}}</h2>
            <h1>&#x24; {{auction.current_bid}}</h1>
            <form action="{% url 'auctions:create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="numeric" name="bid" step=0.01 min="{{auction.current_bid}}" placeholder="Your bid">
                </div>
                <input class="btn btn-danger" type="submit" value="Place bid">
            </form>
        </div>
    </section>
    <div>
        <h2>Description:</h2>
        <p class="card-text">{{auction.description}}</p>
        <h2 style="text-align: center;">Bids History</h2>
    </div>
    {% endif %}

{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="date" name="birthday" placeholder="Birthday date" data-date-inline-picker="true">
        </div>
        <div class="form-group">
            <input class="form-control" type="tel" name="telNo" placeholder="Phone number" size="20" minlength="9" maxlength="14">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/wishlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    {% if user.is_authenticated %}
    <h2>Your wishlist</h2>
    {% for auction in watchlist.auctions.all %}
      <div class="card mb-3">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="{{ auction.image_obj.image.url }}" class="img-fluid rounded-start" style="max-height: 300px;border-radius: 5px;">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{auction.title}}</h5>
                <h6 class="card-text" style="font-weight: bold;">Price: {{auction.current_bid}} &#128176;</h6>
                <p class="card-text">{{auction.description}}</p>
                <a href="{% url 'auctions:listing' auction_id=auction.id %}" name='mybtn2' class="btn-bid">Make a bid <i class="fa fa-gavel"></i></a>
                <p class="card-text"><small class="text-muted">Created on: {{auction.date_created}}</small></p>
              </div>
            </div>
          </div>
      </div>
    {% endfor %}
    {% endif %}
{% endblock %}